-- Initial seed questions (original LET-style practice material)
-- FLPT is independent and not affiliated with PRC/CHED.

INSERT INTO public.questions (category, subject, topic, difficulty, question, option_a, option_b, option_c, option_d, correct_answer, explanation, reference, source_type) VALUES
-- GENERAL EDUCATION - English
('GENERAL_EDUCATION', 'English', 'Grammar and Usage', 'EASY',
 'Which of the following sentences is grammatically correct?',
 'Neither of the students have submitted their papers.',
 'Neither of the students has submitted his or her paper.',
 'Neither of the students have submitted his paper.',
 'Neither of the students has submitted their papers.',
 'B',
 'When "neither" is the subject, it takes a singular verb ("has"). Using "his or her" maintains agreement and avoids the informal plural "their" in formal contexts.',
 'Basic English grammar conventions', 'original'),

('GENERAL_EDUCATION', 'English', 'Vocabulary', 'MODERATE',
 'The word "ubiquitous" most nearly means:',
 'Rare and valuable',
 'Present everywhere',
 'Difficult to understand',
 'Outdated',
 'B',
 'Ubiquitous means existing or being everywhere at the same time; constantly encountered.',
 'English vocabulary development', 'original'),

('GENERAL_EDUCATION', 'English', 'Reading Comprehension', 'MODERATE',
 'In academic writing, a thesis statement should primarily:',
 'Summarize the entire paper in one sentence',
 'Present the main argument or claim of the paper',
 'List all sources used in the research',
 'Provide background information only',
 'B',
 'A thesis statement clearly presents the central argument or claim that the rest of the paper will support and develop.',
 'Academic writing principles', 'original'),

-- GENERAL EDUCATION - Mathematics
('GENERAL_EDUCATION', 'Mathematics', 'Number Sense', 'EASY',
 'What is 15% of 240?',
 '24',
 '36',
 '30',
 '42',
 'B',
 '15% = 0.15. 0.15 × 240 = 36.',
 'Basic percentage calculations', 'original'),

('GENERAL_EDUCATION', 'Mathematics', 'Algebra', 'MODERATE',
 'If 2x + 5 = 17, what is the value of x?',
 '5',
 '6',
 '7',
 '8',
 'B',
 '2x + 5 = 17 → 2x = 12 → x = 6.',
 'Solving linear equations', 'original'),

('GENERAL_EDUCATION', 'Mathematics', 'Geometry', 'MODERATE',
 'The area of a rectangle with length 12 cm and width 5 cm is:',
 '17 cm²',
 '34 cm²',
 '60 cm²',
 '24 cm²',
 'C',
 'Area of rectangle = length × width = 12 × 5 = 60 cm².',
 'Basic geometry formulas', 'original'),

-- GENERAL EDUCATION - Science
('GENERAL_EDUCATION', 'Science', 'Biology', 'EASY',
 'Which organelle is primarily responsible for producing energy in animal cells?',
 'Nucleus',
 'Mitochondria',
 'Ribosome',
 'Golgi apparatus',
 'B',
 'Mitochondria are known as the powerhouse of the cell because they generate most of the cell''s supply of ATP through cellular respiration.',
 'Cell biology fundamentals', 'original'),

('GENERAL_EDUCATION', 'Science', 'Physics', 'MODERATE',
 'Newton''s First Law of Motion states that an object at rest stays at rest unless acted upon by:',
 'Gravity only',
 'An unbalanced force',
 'Friction only',
 'A balanced force',
 'B',
 'Newton''s First Law (law of inertia) states that an object will remain at rest or in uniform motion unless acted upon by an unbalanced (net) force.',
 'Newtonian mechanics', 'original'),

-- GENERAL EDUCATION - Filipino
('GENERAL_EDUCATION', 'Filipino', 'Wika at Gramatika', 'EASY',
 'Alin sa mga sumusunod ang wastong pagbabaybay?',
 'Nakakapagpabagabag',
 'Nakapagpapabagabag',
 'Nakakapagbabagabag',
 'Nakapagpabagabag',
 'A',
 'Ang wastong anyo ay "nakakapagpabagabag" ayon sa mga tuntunin ng pagbubuo ng salita sa Filipino.',
 'Mga tuntunin sa ortograpiyang Filipino', 'original'),

-- GENERAL EDUCATION - Social Science
('GENERAL_EDUCATION', 'Social Science', 'Philippine History', 'MODERATE',
 'Who is considered the founder of the Katipunan?',
 'Jose Rizal',
 'Andres Bonifacio',
 'Emilio Aguinaldo',
 'Apolinario Mabini',
 'B',
 'Andres Bonifacio founded the Kataastaasang Kagalanggalangang Katipunan ng mga Anak ng Bayan (KKK) in 1892.',
 'Philippine revolutionary history', 'original'),

-- PROFESSIONAL EDUCATION
('PROFESSIONAL_EDUCATION', 'Assessment of Learning', 'Principles of Assessment', 'MODERATE',
 'Which of the following best describes formative assessment?',
 'Assessment given at the end of a unit to assign grades',
 'Ongoing assessment used to monitor learning and provide feedback',
 'A standardized test administered once a year',
 'Assessment used solely for ranking students',
 'B',
 'Formative assessment is continuous and diagnostic; it informs both teaching and learning during the instructional process rather than only at the end.',
 'Assessment principles in education', 'original'),

('PROFESSIONAL_EDUCATION', 'Assessment of Learning', 'Types of Assessment', 'EASY',
 'A teacher gives a short quiz after each lesson to check understanding. This is an example of:',
 'Summative assessment',
 'Formative assessment',
 'Diagnostic assessment only',
 'Norm-referenced assessment',
 'B',
 'Quizzes given during instruction to check understanding and guide next steps are classic formative assessments.',
 'Classroom assessment practices', 'original'),

('PROFESSIONAL_EDUCATION', 'Curriculum Development', 'Curriculum Models', 'MODERATE',
 'Which curriculum design organizes content around major themes or issues rather than traditional subjects?',
 'Subject-centered',
 'Learner-centered',
 'Problem-centered or thematic',
 'Core curriculum only',
 'C',
 'Problem-centered or thematic curriculum integrates knowledge around real-world problems or themes instead of discrete subject silos.',
 'Curriculum design approaches', 'original'),

('PROFESSIONAL_EDUCATION', 'Child and Adolescent Development', 'Developmental Theories', 'MODERATE',
 'According to Piaget, children in the concrete operational stage (ages 7–11) can typically:',
 'Think abstractly about hypothetical situations',
 'Perform logical operations on concrete objects and events',
 'Only engage in sensorimotor exploration',
 'Fully grasp formal scientific reasoning',
 'B',
 'In the concrete operational stage, children can reason logically about concrete objects and events but still struggle with abstract and hypothetical thinking.',
 'Piaget''s stages of cognitive development', 'original'),

('PROFESSIONAL_EDUCATION', 'Educational Technology', 'ICT Integration', 'EASY',
 'Which of the following is the most important consideration when integrating technology into a lesson?',
 'Using the newest available device',
 'Aligning the technology with learning objectives',
 'Ensuring every student has a personal device',
 'Replacing all traditional materials',
 'B',
 'Technology should serve pedagogy. The primary criterion is whether the tool helps achieve the intended learning outcomes.',
 'TPACK and effective ICT integration', 'original'),

('PROFESSIONAL_EDUCATION', 'Teaching Profession', 'Professional Ethics', 'MODERATE',
 'A teacher discovers that a colleague is consistently late and unprepared. The most professional first step is to:',
 'Report immediately to the principal without discussion',
 'Discuss the concern privately and constructively with the colleague if appropriate',
 'Ignore the situation completely',
 'Tell other teachers about it',
 'B',
 'Professional ethics encourage addressing concerns collegially and constructively when possible before escalating, while still protecting student welfare.',
 'Code of Ethics for Professional Teachers (Philippines)', 'original'),

('PROFESSIONAL_EDUCATION', 'Facilitating Learning', 'Learning Theories', 'MODERATE',
 'In constructivist learning theory, knowledge is primarily:',
 'Transmitted directly from teacher to student',
 'Constructed by the learner through experience and reflection',
 'Innate and unfolds naturally without instruction',
 'Memorized through repetition alone',
 'B',
 'Constructivism posits that learners actively build knowledge by connecting new information to prior experiences and reflecting on them.',
 'Constructivist approaches to learning', 'original'),

('PROFESSIONAL_EDUCATION', 'Principles of Teaching', 'Lesson Planning', 'EASY',
 'The "ABCs" of writing specific learning objectives typically refer to:',
 'Audience, Behavior, Condition (and Degree)',
 'Activity, Book, Content',
 'Assessment, Behavior, Curriculum',
 'Aim, Basis, Conclusion',
 'A',
 'Effective objectives specify the Audience (who), Behavior (what observable action), Condition (under what circumstances), and often Degree (to what standard).',
 'Writing instructional objectives', 'original'),

('PROFESSIONAL_EDUCATION', 'Social Dimensions of Education', 'Education and Society', 'MODERATE',
 'The function of education that transmits cultural values and social norms is known as:',
 'Economic function',
 'Socialization or cultural transmission',
 'Selective function only',
 'Political indoctrination exclusively',
 'B',
 'One primary sociological function of education is socialization—passing on the culture, values, and norms of society to the next generation.',
 'Sociology of education', 'original'),

('PROFESSIONAL_EDUCATION', 'Assessment of Learning', 'Test Construction', 'DIFFICULT',
 'A test item that can be answered correctly by students who have not learned the intended content but use test-taking strategies is said to have low:',
 'Reliability',
 'Validity (content or construct)',
 'Difficulty index only',
 'Discrimination only',
 'B',
 'If an item can be answered without the intended knowledge, it does not validly measure the target construct or content, reducing validity.',
 'Principles of educational measurement', 'original');
